//! Exposing the managed DuckDB database over the Quack protocol.
//!
//! [Quack](https://duckdb.org/docs/current/quack/overview) turns a DuckDB
//! instance into an HTTP server that other DuckDB clients can `ATTACH` to.
//! That is the whole purpose of this module: the engine keeps sole ownership
//! of the database and remains the only writer on the ingest path, while
//! other processes — the webapp, spark-adsb, an ad-hoc `duckdb` CLI — get
//! live SQL access instead of being locked out by the exclusive file lock.
//!
//! # Two things to know before using this
//!
//! **The extension is fetched at runtime.** `quack` is *not* statically
//! linked into the bundled DuckDB build (`libduckdb-sys` links only
//! `core_functions`, `parquet` and `json`), so the first `INSTALL quack`
//! downloads it from `extensions.duckdb.org`. Offline, sharing is simply
//! unavailable — which is why every failure here is reported as
//! [`ShareStatus::Unavailable`] rather than propagated as a fatal error.
//!
//! **A token grants full read *and* write access** to every table, because
//! the server runs with Quack's default permissive authorization. Quack's
//! authorization hook is a SQL macro, and macros cannot execute DML, so
//! table-level rules are not expressible without shipping a custom DuckDB
//! extension. Bind to localhost unless you have fronted it with a
//! TLS-terminating reverse proxy — the Quack server does no TLS itself.

use crate::error::StorageError;
use crate::types::{ShareConfig, ShareInfo};
use duckdb::Connection;
use tracing::info;

/// Escape a single-quoted SQL string literal.
///
/// The URI and token reach us from configuration, and `quack_serve` takes
/// them positionally in SQL text, so they must be escaped rather than
/// interpolated raw.
fn sql_quote(value: &str) -> String {
    value.replace('\'', "''")
}

/// Install and load the `quack` extension.
///
/// Reaches the network on first use; subsequent calls hit the local
/// extension cache.
pub(crate) fn load_extension(conn: &Connection) -> Result<(), StorageError> {
    conn.execute_batch("INSTALL quack; LOAD quack;")?;
    Ok(())
}

/// Start a Quack server on `conn`'s database instance.
///
/// Returns the coordinates clients need: the listen URI, the HTTP URL, and
/// the auth token (generated by DuckDB when `cfg.token` is `None`).
pub(crate) fn start(conn: &Connection, cfg: &ShareConfig) -> Result<ShareInfo, StorageError> {
    load_extension(conn)?;

    let mut args = format!("'{}'", sql_quote(&cfg.uri));
    if let Some(token) = &cfg.token {
        args.push_str(&format!(", token := '{}'", sql_quote(token)));
    }
    if cfg.allow_other_hostname {
        args.push_str(", allow_other_hostname := true");
    }

    // `quack_serve` returns exactly one row: (listen_uri, listen_url, auth_token).
    let info = conn.query_row(&format!("CALL quack_serve({args})"), [], |row| {
        Ok(ShareInfo {
            listen_uri: row.get(0)?,
            listen_url: row.get(1)?,
            token: row.get(2)?,
        })
    })?;

    info!("Database shared over Quack at {}", info.listen_uri);
    Ok(info)
}

/// Stop the Quack server listening on `listen_uri`.
///
/// Pass the `listen_uri` returned by [`start`], not the configured URI — the
/// former has the port resolved.
pub(crate) fn stop(conn: &Connection, listen_uri: &str) -> Result<(), StorageError> {
    conn.execute_batch(&format!("CALL quack_stop('{}')", sql_quote(listen_uri)))?;
    info!("Stopped sharing {listen_uri}");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sql_quote_escapes_embedded_single_quotes() {
        assert_eq!(sql_quote("quack:localhost"), "quack:localhost");
        assert_eq!(sql_quote("it's"), "it''s");
        // The case that matters: a token crafted to break out of the literal.
        assert_eq!(
            sql_quote("'); DROP TABLE positions; --"),
            "''); DROP TABLE positions; --"
        );
    }
}
