#!/usr/bin/env python3
"""Render adsb-stack.toml into the per-binary configs the Rust loaders read.

Exists because `source_id` and the MQTT broker/port/topic are needed by *both*
`adsb-pulsar-client` and `adsb-data-server`. Hand-maintained in two files they
drift, and the failure is silent: a feed publishing to one topic while the
recorder subscribes to another looks healthy from both sides and records
nothing.

Output goes to .run/, which is gitignored -- these are derived artifacts.

TOML is emitted by hand: `tomllib` is read-only and `tomli_w` is not installed,
and adding a dependency to render ~20 keys is not worth it.
"""
import sys
import tomllib
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
STACK = REPO / "adsb-stack.toml"
OUT = REPO / ".run"

HEADER = """# GENERATED by scripts/render-config.py -- DO NOT EDIT.
# Edit adsb-stack.toml and run `make render`; changes here are overwritten.
"""


def q(value) -> str:
    """Render a Python value as a TOML scalar."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return '"{}"'.format(str(value).replace('\\', '\\\\').replace('"', '\\"'))


def emit(pairs) -> str:
    return "\n".join(f"{k} = {q(v)}" for k, v in pairs if v is not None) + "\n"


def render_feed(cfg: dict) -> str:
    rx, d, m, p = cfg["receiver"], cfg["dump1090"], cfg["mqtt"], cfg["pulsar"]

    # The forwarder list is what makes a deployment "no-Pulsar" or not, so it is
    # derived from [pulsar].enabled rather than repeated by hand.
    forwarders = ["mqtt"] + (["pulsar"] if p.get("enabled") else [])

    body = emit([
        ("source_id", rx["id"]),
        ("socket_host", d["host"]),
        ("socket_port", d["port"]),
        ("connection_mode", "client"),
        ("dump1090_tz", rx.get("timezone", "Local")),
    ])
    body += "\nforwarders = [{}]\n".format(", ".join(q(f) for f in forwarders))
    body += "\n" + emit([
        ("mqtt_broker", m["host"]),
        ("mqtt_port", m["port"]),
        ("mqtt_topic", m["topic"]),
        ("mqtt_qos", m.get("qos", 0)),
    ])
    if p.get("enabled"):
        body += "\n" + emit([
            ("pulsar_broker", p["broker"]),
            ("pulsar_topic", p["topic"]),
        ])
    # arg(skip) fields: settable from the file only, never from a flag.
    body += "\n" + emit([
        ("receiver_latitude", rx.get("latitude")),
        ("receiver_longitude", rx.get("longitude")),
        ("receiver_altitude", rx.get("altitude_ft")),
    ])
    return HEADER + "\n" + body


def render_server(cfg: dict) -> str:
    rx, m, s = cfg["receiver"], cfg["mqtt"], cfg["storage"]

    # Relative db_path is resolved against the repo root, so `make up` works
    # from anywhere and the dev database lands in .run/ rather than $PWD.
    db_path = Path(s["db_path"])
    if not db_path.is_absolute():
        db_path = REPO / db_path

    pairs = [
        ("source_id", rx["id"]),
        ("db_path", str(db_path)),
        ("mqtt_broker", m["host"]),
        ("mqtt_port", m["port"]),
        ("mqtt_topic", m["topic"]),
        ("dump1090_tz", rx.get("timezone", "Local")),
        ("checkpoint_secs", s.get("checkpoint_secs", 300)),
        ("retention_hours", s.get("retention_hours", 0)),
        ("http_port", s.get("http_port", 8787)),
        ("share", s.get("share", False)),
        ("share_uri", s.get("share_uri", "quack:0.0.0.0:9494")),
    ]
    token = s.get("share_token")
    if s.get("share") and token:
        pairs.append(("share_token", token))
    return HEADER + "\n" + emit(pairs)


def main() -> int:
    if not STACK.exists():
        print(f"error: {STACK} not found", file=sys.stderr)
        return 1
    with STACK.open("rb") as fh:
        cfg = tomllib.load(fh)

    OUT.mkdir(exist_ok=True)
    for name, text in (
        ("feed.toml", render_feed(cfg)),
        ("data-server.toml", render_server(cfg)),
    ):
        (OUT / name).write_text(text)
        print(f"  rendered .run/{name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
