#!/usr/bin/env python3
"""Render one authored config into the per-binary configs the Rust loaders read.

Exists because `source_id` and the MQTT broker/port/topic are needed by *both*
`adsb-pulsar-client` and `adsb-data-server`. Hand-maintained in two files they
drift, and the failure is silent: a feed publishing to one topic while the
recorder subscribes to another looks healthy from both sides and records
nothing.

Two modes, same reasoning applied at two scales:

    render-config.py                     adsb-stack.toml -> .run/*.toml
    render-config.py <stack> <outdir>    a named stack, e.g. .run/prod/
                                         one machine, the development stack

    render-config.py --fleet deploy/prod.toml
                                         one fleet file -> deploy/.rendered/<node>/
                                         several hosts, shipped by `make deploy`

The fleet mode adds a third invariant to the two above: the Quack `share_token`
must match between the recorder and whoever attaches to it.

Output directories are gitignored -- these are derived artifacts.

TOML is emitted by hand: `tomllib` is read-only and `tomli_w` is not installed,
and adding a dependency to render ~20 keys is not worth it.
"""
import sys
import tomllib
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# Defaults for the unnamed stack. Both are overridable so that several stacks
# can be rendered side by side without overwriting each other -- see
# `stack.sh paths`, which is what passes these in.
STACK = REPO / "adsb-stack.toml"
OUT = REPO / ".run"

HEADER = """# GENERATED by scripts/render-config.py -- DO NOT EDIT.
# Edit adsb-stack.toml and run `make render`; changes here are overwritten.
"""

FLEET_HEADER = """# GENERATED by scripts/render-config.py --fleet -- DO NOT EDIT.
# Edit the fleet file and re-render; changes here are overwritten.
# Install on the node with install-edge.sh, which will not clobber an existing
# /etc/adsb config -- a new one lands as *.toml.new.
"""


def q(value) -> str:
    """Render a Python value as a TOML scalar."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return '"{}"'.format(str(value).replace('\\', '\\\\').replace('"', '\\"'))


def emit(pairs) -> str:
    return "\n".join(f"{k} = {q(v)}" for k, v in pairs if v is not None) + "\n"


def render_feed(cfg: dict, out: Path = OUT) -> str:
    rx, d, m, p = cfg["receiver"], cfg["dump1090"], cfg["mqtt"], cfg["pulsar"]

    # The forwarder list is what makes a deployment "no-Pulsar" or not, so it is
    # derived from [pulsar].enabled rather than repeated by hand.
    forwarders = ["mqtt"] + (["pulsar"] if p.get("enabled") else [])

    body = emit([
        ("source_id", rx["id"]),
        ("socket_host", d["host"]),
        ("socket_port", d["port"]),
        ("connection_mode", "client"),
        ("dump1090_tz", rx.get("timezone", "Local")),
    ])
    body += "\nforwarders = [{}]\n".format(", ".join(q(f) for f in forwarders))
    body += "\n" + emit([
        ("mqtt_broker", m["host"]),
        ("mqtt_port", m["port"]),
        ("mqtt_topic", m["topic"]),
        ("mqtt_qos", m.get("qos", 0)),
    ])
    if p.get("enabled"):
        body += "\n" + emit([
            ("pulsar_broker", p["broker"]),
            ("pulsar_topic", p["topic"]),
        ])
    # arg(skip) fields: settable from the file only, never from a flag.
    body += "\n" + emit([
        ("receiver_latitude", rx.get("latitude")),
        ("receiver_longitude", rx.get("longitude")),
        ("receiver_altitude", rx.get("altitude_ft")),
    ])
    return HEADER + "\n" + body


def render_server(cfg: dict, out: Path = OUT) -> str:
    rx, m, s = cfg["receiver"], cfg["mqtt"], cfg["storage"]

    # A relative db_path is resolved against the repo root so `make up` works
    # from anywhere and the database lands in .run/ rather than $PWD.
    #
    # `.run/<file>` is rewritten into THIS stack's run directory: two stacks
    # both saying ".run/adsb.db" must not end up sharing one DuckDB file, and
    # DuckDB takes an exclusive lock, so the second would simply fail to open.
    db_path = Path(s["db_path"])
    if not db_path.is_absolute():
        parts = db_path.parts
        if parts and parts[0] == ".run":
            db_path = out.joinpath(*parts[1:])
        else:
            db_path = REPO / db_path

    pairs = [
        ("source_id", rx["id"]),
        ("db_path", str(db_path)),
        ("mqtt_broker", m["host"]),
        ("mqtt_port", m["port"]),
        ("mqtt_topic", m["topic"]),
        ("dump1090_tz", rx.get("timezone", "Local")),
        ("checkpoint_secs", s.get("checkpoint_secs", 300)),
        ("retention_hours", s.get("retention_hours", 0)),
        ("http_port", s.get("http_port", 8787)),
        ("share", s.get("share", False)),
        ("share_uri", s.get("share_uri", "quack:0.0.0.0:9494")),
    ]
    token = s.get("share_token")
    if s.get("share") and token:
        pairs.append(("share_token", token))
    return HEADER + "\n" + emit(pairs)


# --- fleet mode -------------------------------------------------------------
#
# A fleet file describes one STAGE of one site: the identities, the broker, and
# the two node roles. Everything shared between the nodes is written once here
# and composed into both outputs, which is the point -- see the module docstring.


def stage_of(fleet: dict) -> str:
    """The deployment stage. Required: it is half of every identity."""
    return fleet["stage"]


def fleet_source_id(fleet: dict) -> str:
    """`<site>-<stage>`, identical on the feed node and the recorder.

    Identical is deliberate. The recorder stamps its OWN source_id onto every
    stored record, so a mismatch makes the data claim the wrong receiver. They
    do not collide on the broker because a subscriber's MQTT client id gets a
    `-sub` suffix (see source/mqtt_source.rs).
    """
    return f"{fleet['site']['id']}-{stage_of(fleet)}"


def fleet_topic(fleet: dict) -> str:
    """`adsb/<stage>/sbs/raw`, unless the fleet names one explicitly.

    Scoping the topic by stage is the stronger of the two isolation guards:
    distinct client ids stop clients evicting each other, but only a distinct
    topic stops a dev feed writing into the prod recorder's database.
    """
    explicit = fleet.get("broker", {}).get("topic")
    return explicit if explicit else f"adsb/{stage_of(fleet)}/sbs/raw"


def node_dir(host: str) -> str:
    """Directory name for a node's rendered config.

    The short hostname, so `deploy/.rendered/pi3/` pairs obviously with
    `make deploy PI_HOST=pi@pi3.lan`. An IP address is kept whole -- splitting
    it on the first dot would produce a directory called "192".
    """
    labels = host.split(".")
    if len(labels) == 4 and all(l.isdigit() for l in labels):
        return host
    return labels[0]


def render_fleet_feed(fleet: dict) -> str:
    site, broker = fleet["site"], fleet["broker"]
    node = fleet["nodes"]["feed"]
    pulsar = fleet.get("pulsar", {})

    forwarders = ["mqtt"] + (["pulsar"] if pulsar.get("enabled") else [])

    body = emit([
        ("source_id", fleet_source_id(fleet)),
        ("socket_host", node.get("dump1090_host", "127.0.0.1")),
        ("socket_port", node.get("dump1090_port", 30003)),
        ("connection_mode", "client"),
        ("dump1090_tz", site.get("timezone", "Local")),
    ])
    body += "\nforwarders = [{}]\n".format(", ".join(q(f) for f in forwarders))
    body += "\n" + emit([
        # The feed always crosses the network to reach the broker unless it
        # happens to host it; addressing it by name is correct either way.
        ("mqtt_broker", broker["host"]),
        ("mqtt_port", broker.get("port", 1883)),
        ("mqtt_topic", fleet_topic(fleet)),
        ("mqtt_qos", broker.get("qos", 0)),
    ])
    if pulsar.get("enabled"):
        body += "\n" + emit([
            ("pulsar_broker", pulsar["broker"]),
            ("pulsar_topic", pulsar["topic"]),
        ])
    # arg(skip) fields: settable from the file only, never from a flag.
    body += "\n" + emit([
        ("receiver_latitude", site.get("latitude")),
        ("receiver_longitude", site.get("longitude")),
        ("receiver_altitude", site.get("altitude_ft")),
    ])
    return FLEET_HEADER + "\n" + body


def render_fleet_server(fleet: dict) -> str:
    site, broker = fleet["site"], fleet["broker"]
    node = fleet["nodes"]["recorder"]

    # Co-located with the broker: subscribe over loopback. The recorder is the
    # durable leg, so it should not depend on the network when it does not have
    # to -- only the lossy legs (the feed, the desktop) need to cross the LAN.
    co_located = node.get("host") == broker["host"]
    mqtt_broker = "127.0.0.1" if co_located else broker["host"]

    pairs = [
        ("source_id", fleet_source_id(fleet)),
        # Left exactly as written: this is the NODE's path, not a path on the
        # machine doing the rendering, so the dev mode's repo-relative
        # resolution would be actively wrong here.
        ("db_path", node.get("db_path", "/var/lib/adsb/adsb.db")),
        ("mqtt_broker", mqtt_broker),
        ("mqtt_port", broker.get("port", 1883)),
        ("mqtt_topic", fleet_topic(fleet)),
        ("dump1090_tz", site.get("timezone", "Local")),
        ("gap_threshold_ms", node.get("gap_threshold_ms", 3600000)),
        ("checkpoint_secs", node.get("checkpoint_secs", 300)),
        ("retention_hours", node.get("retention_hours", 0)),
        ("http_port", node.get("http_port", 8787)),
        ("share", node.get("share", False)),
        ("share_uri", node.get("share_uri", "quack:0.0.0.0:9494")),
    ]
    token = node.get("share_token")
    if node.get("share") and token:
        pairs.append(("share_token", token))
    return FLEET_HEADER + "\n" + emit(pairs)


def render_fleet(path: Path) -> int:
    if not path.exists():
        print(f"error: {path} not found", file=sys.stderr)
        return 1
    with path.open("rb") as fh:
        fleet = tomllib.load(fh)

    try:
        stage_of(fleet)
    except KeyError:
        print(f"error: {path} has no `stage` -- it is half of every identity "
              "(see deploy/README.md)", file=sys.stderr)
        return 1

    out = REPO / "deploy" / ".rendered"
    for role, filename, render in (
        ("feed", "feed.toml", render_fleet_feed),
        ("recorder", "data-server.toml", render_fleet_server),
    ):
        node = fleet.get("nodes", {}).get(role)
        if node is None:
            print(f"  no [nodes.{role}] -- skipped")
            continue
        d = out / node_dir(node["host"])
        d.mkdir(parents=True, exist_ok=True)
        (d / filename).write_text(render(fleet))
        print(f"  rendered deploy/.rendered/{d.name}/{filename}"
              f"  ({node['host']})")
    return 0


def render_stack(stack: Path, out: Path) -> int:
    if not stack.exists():
        print(f"error: {stack} not found", file=sys.stderr)
        return 1
    with stack.open("rb") as fh:
        cfg = tomllib.load(fh)

    out.mkdir(parents=True, exist_ok=True)
    for name, text in (
        ("feed.toml", render_feed(cfg, out)),
        ("data-server.toml", render_server(cfg, out)),
    ):
        (out / name).write_text(text)
        try:
            shown = out.relative_to(REPO)
        except ValueError:
            shown = out
        print(f"  rendered {shown}/{name}")
    return 0


def main() -> int:
    if len(sys.argv) > 1 and sys.argv[1] == "--fleet":
        if len(sys.argv) != 3:
            print("usage: render-config.py --fleet <fleet.toml>", file=sys.stderr)
            return 2
        return render_fleet(Path(sys.argv[2]))

    if len(sys.argv) == 3:
        return render_stack(Path(sys.argv[1]), Path(sys.argv[2]))
    if len(sys.argv) == 1:
        return render_stack(STACK, OUT)
    print("usage: render-config.py [<stack.toml> <outdir>] | [--fleet <fleet.toml>]",
          file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main())
